/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JList;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
        
/**
 *
 * @author Harja
 */
public class transaction extends javax.swing.JFrame {
    private DefaultTableModel tempCart;
    private String SQL;
    database.connect DB = new database.connect();
    Connection con;
    Statement stat;
    java.sql.ResultSet ResultSet;
    java.sql.PreparedStatement PreparedStatement;
    public ResultSet rs;

    /**
     * Creates new form transaction
     */
    
    
    private void searchMenu(String key) {
        DB.config();
        con=DB.con;
        stat=DB.stm;
        try {
            SQL = "SELECT * FROM products WHERE product LIKE '%"+key+"%'";
            ResultSet data = stat.executeQuery(SQL);
            DefaultListModel menuList = new DefaultListModel();
            System.out.println(menuList);
            jList_menuList.setModel(menuList);
            while (data.next()) {
                String product = data.getString("product");
                menuList.addElement(product);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void showMenuList() {
        database.connect DB = new database.connect();
        DB.config();
        con=DB.con;
        stat=DB.stm;
        try {
            SQL = "SELECT * FROM products";
            ResultSet data = stat.executeQuery(SQL);
            DefaultListModel menuList = new DefaultListModel();
            System.out.println(menuList);
            jList_menuList.setModel(menuList);
            while (data.next()) {
                String product = data.getString("product");
                menuList.addElement(product);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
                
    }
    
    public void showTempCart() {
        tempCart = new DefaultTableModel();
        tempCart.addColumn("Kode");
        tempCart.addColumn("Produk");
        tempCart.addColumn("Harga Satuan");
        tempCart.addColumn("Jumlah Beli");
        tempCart.addColumn("Total Harga");
        
        jTable_tempCart.setModel(tempCart);
        database.connect DB = new database.connect();
        DB.config();
        con=DB.con;
        stat=DB.stm;
        tempCart.getDataVector().removeAllElements();
        try {
            SQL = "SELECT * FROM temp_cart";
            ResultSet res = stat.executeQuery(SQL);
            while (res.next()){
                tempCart.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("product"),
                    res.getString("price"),
                    res.getString("purchase_amount"),
                    res.getString("total_price")
                });
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Failed");
        }
    }
    
    public transaction() {
        initComponents();
        this.setLocationRelativeTo(null);
        showMenuList();
        showTempCart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_menuList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jText_Field_searchMenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_code = new javax.swing.JTextField();
        jTextField_product = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_price = new javax.swing.JTextField();
        jTextField_stock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton_addToCart = new javax.swing.JButton();
        jTextField_purchaseAmount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton_back_to_dashboard = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_tempCart = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jTextField_tempCartSelectedProduct = new javax.swing.JTextField();
        jButton_deleteSelectedProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("WELCOME TO");

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("CAFELINE");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/java.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(481, 481, 481)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jList_menuList.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jList_menuList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_menuList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList_menuList.setSelectionBackground(new java.awt.Color(204, 102, 0));
        jList_menuList.setSelectionForeground(new java.awt.Color(255, 204, 153));
        jList_menuList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_menuListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList_menuList);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 0));
        jLabel4.setText("DAFTAR PRODUK");

        jText_Field_searchMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jText_Field_searchMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jText_Field_searchMenuKeyReleased(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 102, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 0));
        jLabel5.setText("Cari Produk");

        jTextField_code.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_code.setEnabled(false);
        jTextField_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codeActionPerformed(evt);
            }
        });

        jTextField_product.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_product.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_product.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 0));
        jLabel6.setText("Nama Produk");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 0));
        jLabel7.setText("DETAIL PRODUK");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 0));
        jLabel8.setText("Harga Produk");

        jTextField_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_price.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_price.setEnabled(false);

        jTextField_stock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_stock.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_stock.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 0));
        jLabel9.setText("Stok Produk");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 0));
        jLabel10.setText("Kode Produk");

        jButton_addToCart.setBackground(new java.awt.Color(204, 102, 0));
        jButton_addToCart.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_addToCart.setForeground(new java.awt.Color(255, 204, 153));
        jButton_addToCart.setText("Masukkan Keranjang");
        jButton_addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addToCartActionPerformed(evt);
            }
        });

        jTextField_purchaseAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_purchaseAmount.setToolTipText("Jumlah");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 0));
        jLabel11.setText("Jumlah");

        jButton_back_to_dashboard.setBackground(new java.awt.Color(255, 204, 153));
        jButton_back_to_dashboard.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton_back_to_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        jButton_back_to_dashboard.setText("Kembali");
        jButton_back_to_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_back_to_dashboardActionPerformed(evt);
            }
        });

        jTable_tempCart.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTable_tempCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_tempCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tempCartMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_tempCart);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 0));
        jLabel12.setText("Keranjang");

        jTextField_tempCartSelectedProduct.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField_tempCartSelectedProduct.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_tempCartSelectedProduct.setEnabled(false);

        jButton_deleteSelectedProduct.setBackground(new java.awt.Color(204, 102, 0));
        jButton_deleteSelectedProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_deleteSelectedProduct.setForeground(new java.awt.Color(255, 204, 153));
        jButton_deleteSelectedProduct.setText("Hapus");
        jButton_deleteSelectedProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteSelectedProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(335, 335, 335))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jText_Field_searchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(120, 120, 120)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_tempCartSelectedProduct)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_deleteSelectedProduct))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField_product, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                                .addComponent(jTextField_price, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel7))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField_code, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_stock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jTextField_purchaseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_addToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_back_to_dashboard)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_back_to_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jText_Field_searchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_code, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jTextField_product))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_addToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_purchaseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(54, 54, 54))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jButton_deleteSelectedProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_tempCartSelectedProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_menuListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_menuListMouseClicked
        try {
            String selected = jList_menuList.getSelectedValue();
            String SQL = "SELECT * FROM products WHERE product = '"+ selected +"'";
            ResultSet data = stat.executeQuery(SQL);
            if (data.next()) {
                String code = data.getString("id");
                String product = data.getString("product");
                String price = data.getString("price");
                String stock = data.getString("stock");

                jTextField_code.setText(code);
                jTextField_product.setText(product);
                jTextField_price.setText(price);
                jTextField_stock.setText(stock);
            } else {
                // Data tidak ditemukan, atur jTextField ke nilai default atau kosong
                jTextField_code.setText("");
                jTextField_product.setText("");
                jTextField_price.setText("");
                jTextField_stock.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jList_menuListMouseClicked

    private void jText_Field_searchMenuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_Field_searchMenuKeyReleased
        String key = jText_Field_searchMenu.getText();
        if (!"".equals(key)) {
            searchMenu(key);
        } else {
            showMenuList();
        }
    }//GEN-LAST:event_jText_Field_searchMenuKeyReleased

    private void jTextField_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codeActionPerformed

    private void jButton_addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addToCartActionPerformed
        DB.config();
        String code = jTextField_code.getText();
        String product = jTextField_product.getText();
        String priceStr = jTextField_price.getText();
        String purchaseAmountStr = jTextField_purchaseAmount.getText();
        String stockStr = jTextField_stock.getText();
        int purchaseAmount = Integer.parseInt(purchaseAmountStr);
        int stock = Integer.parseInt(stockStr);
        if (purchaseAmount > stock) {
            JOptionPane.showMessageDialog(null, "Stok produk tidak tersedia");
        } else {
            try {
                String selected = jTextField_code.getText();
                int reduceStock = stock-purchaseAmount;
                int price = Integer.parseInt(priceStr);
                int totalPrice = price*purchaseAmount;
                String reduceStockQuery = "UPDATE `products` SET stock='"+reduceStock+"' WHERE id='"+selected+"'";
                PreparedStatement stm = con.prepareStatement(reduceStockQuery);
                stm.executeUpdate();
                SQL = "INSERT INTO temp_cart (id,product,price,total_price,purchase_amount) VALUES ('"+code+"','"+product+"','"+price+"','"+totalPrice+"','"+purchaseAmount+"')";
                PreparedStatement stat = con.prepareStatement(SQL);
                stat.execute();
                jTextField_code.setText("");
                jTextField_product.setText("");
                jTextField_price.setText("");
                jTextField_stock.setText("");
                jTextField_purchaseAmount.setText("");
                showMenuList();
                showTempCart();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton_addToCartActionPerformed

    private void jButton_back_to_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_back_to_dashboardActionPerformed
        dashboard start=new dashboard();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_back_to_dashboardActionPerformed

    private void jButton_deleteSelectedProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteSelectedProductActionPerformed
        try {
            DB.config();
            int tempCartRow = jTable_tempCart.getSelectedRow();
            String code = tempCart.getValueAt(tempCartRow, 0).toString();
            String selectProduct = "SELECT * FROM products WHERE id = '"+code+"'";
            ResultSet data = stat.executeQuery(selectProduct);
            if (data.next()) {
                String stockStr = data.getString("stock");
                String purchaseAmountStr = tempCart.getValueAt(tempCartRow, 3).toString();
                int stock = Integer.parseInt(stockStr);
                int purchaseAmount = Integer.parseInt(purchaseAmountStr);
                int originalStock = stock+purchaseAmount;
                String backStock = "UPDATE `products` SET stock = '"+ originalStock +"' WHERE id = '"+code+"'";
                PreparedStatement stm = con.prepareStatement(backStock);
                stm.executeUpdate();
            }
            SQL = "DELETE FROM temp_cart WHERE id = '"+code+"'";
            PreparedStatement stm = con.prepareStatement(SQL);
            stm.executeUpdate();
            showTempCart();
            showMenuList();
        } catch (SQLException ex) {
            Logger.getLogger(transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_deleteSelectedProductActionPerformed

    private void jTable_tempCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tempCartMouseClicked
        int row = jTable_tempCart.getSelectedRow();
        jTextField_tempCartSelectedProduct.setText(tempCart.getValueAt(row, 1).toString());
    }//GEN-LAST:event_jTable_tempCartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addToCart;
    private javax.swing.JButton jButton_back_to_dashboard;
    private javax.swing.JButton jButton_deleteSelectedProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList_menuList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_tempCart;
    private javax.swing.JTextField jTextField_code;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextField_product;
    private javax.swing.JTextField jTextField_purchaseAmount;
    private javax.swing.JTextField jTextField_stock;
    private javax.swing.JTextField jTextField_tempCartSelectedProduct;
    private javax.swing.JTextField jText_Field_searchMenu;
    // End of variables declaration//GEN-END:variables
}
